### ISSUE TITLE
全屏的时候，为什么距离底部还有一定的距离呢？

### ISSUE THREAD

**Issue by ihewro** [fashare2015/HoverView#1]
这是我的截图：

![image](https://user-images.githubusercontent.com/20165605/35723965-1a45ecd0-0837-11e8-846a-5ac08c3c2ea3.png)

android sdk 26

**Comment by fashare2015** [comment]
@ihewro `v1.0.2` 修复了这个 bug，maven 仓库改为 `jitpack.io`
